Check for file existence in mumd first

diff --git a/bin/mumd b/bin/mumd
--- a/bin/mumd
+++ b/bin/mumd
@@ -2,7 +2,12 @@
 
 if [[ -z $1 || $1 == '-h' || $1 == '--help' ]]; then
     echo "$0 usage: filename"
-	exit 1
+    exit 1
+fi
+
+if [[ ! -f $1 ]]; then
+    echo "$1 not found"
+    exit 1
 fi
 
 tmpfile=`mktemp -u /tmp/mumdXXXXXXXXXX.pdf`
